import path from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

// The app imports the canonical data modules from ../docs/js (glossary,
// offices, abbreviations, timeline) — single source of truth, so allow the
// dev server to reach one level above this package root.
export default defineConfig({
    plugins: [react(), tailwindcss()],
    resolve: {
        alias: {
            '@': path.resolve(import.meta.dirname, './src'),
            '@data': path.resolve(import.meta.dirname, '../docs/js'),
        },
    },
    server: {
        fs: { allow: ['..'] },
    },
    build: {
        rollupOptions: {
            output: {
                // Stable (unhashed) names: the SSR functions and the baked
                // office pages reference these from a COMMITTED shell
                // (api/_home-shell.html, generated by scripts/build-offices.mjs),
                // which cannot chase a per-build hash. Freshness comes from
                // must-revalidate headers (vercel.json) + the service worker's
                // network-first strategy, same as the vanilla client's /js/*.
                entryFileNames: 'assets/app.js',
                chunkFileNames: 'assets/[name].js',
                assetFileNames: (info) => {
                    const name = info.names?.[0] || info.name || '';
                    return name.endsWith('.css') ? 'assets/app.css' : 'assets/[name][extname]';
                },
                // Vendor split: the framework and the component primitives
                // change far less often than the app code, so returning
                // visitors keep them cached across deploys.
                manualChunks: {
                    vendor: [
                        'react',
                        'react-dom',
                        '@radix-ui/react-accordion',
                        '@radix-ui/react-dialog',
                        '@radix-ui/react-progress',
                        '@radix-ui/react-select',
                        '@radix-ui/react-separator',
                        '@radix-ui/react-slot',
                        '@radix-ui/react-tabs',
                        '@radix-ui/react-tooltip',
                    ],
                },
            },
        },
    },
});
